"""Changed email column name to student_email

Revision ID: 920af0ab67f7
Revises: 791279dd0760
Create Date: 2023-06-03 14:38:50.815841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920af0ab67f7'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('school_email', sa.String(length=55), nullable=True))
    op.drop_column('students', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=55), nullable=True))
    op.drop_column('students', 'school_email')
    # ### end Alembic commands ###